# Generated by Django 5.1.4 on 2024-12-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
