# Generated by Django 5.1.4 on 2024-12-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_attendance_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='latitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='longitude',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
