# Generated by Django 5.1.4 on 2024-12-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_attendance_latitude_alter_attendance_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='media',
            field=models.FileField(null=True, upload_to='proofs/'),
        ),
    ]
