# Generated by Django 5.1.4 on 2024-12-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_work_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
