# Generated by Django 5.1.4 on 2024-12-06 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='media',
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='work',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='work_media/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='api.work')),
            ],
        ),
    ]
