# Generated by Django 5.1.4 on 2024-12-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_course_username_project_username_work_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
