# Generated by Django 5.1.4 on 2024-12-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_project_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proof',
            field=models.FileField(null=True, upload_to='projects/'),
        ),
    ]
