# Generated by Django 5.1.4 on 2024-12-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
