# Generated by Django 5.1.4 on 2024-12-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_attendance_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='due_at',
            field=models.DateTimeField(null=True),
        ),
    ]
